package io.github.waph1.syncer.youtube

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class NetscapeCookiesTest {

    @Test
    fun convertsWebViewCookies() {
        val header = "PREF=f6=40000000&hl=it; SAPISID=abc/def; __Secure-3PAPISID=abc/def; __Host-GAPS=1:xyz"
        val text = NetscapeCookies.fromCookieHeader(header, nowMillis = 1_700_000_000_000)
        val lines = text.lines()
        assertEquals("# Netscape HTTP Cookie File", lines[0])
        val expiry = 1_700_000_000L + 400L * 24 * 3600
        assertTrue(".youtube.com\tTRUE\t/\tTRUE\t$expiry\tPREF\tf6=40000000&hl=it" in lines)
        assertTrue(".youtube.com\tTRUE\t/\tTRUE\t$expiry\tSAPISID\tabc/def" in lines)
        assertTrue("www.youtube.com\tFALSE\t/\tTRUE\t$expiry\t__Host-GAPS\t1:xyz" in lines)
        assertTrue(NetscapeCookies.hasYouTubeSession(text))
        assertTrue(NetscapeCookies.headerHasYouTubeSession(header))
        assertFalse(NetscapeCookies.headerHasYouTubeSession("PREF=x; VISITOR_INFO1_LIVE=y"))
    }

    @Test
    fun keepsOnlyYouTubeCookiesOfABrowserExport() {
        val export = "\uFEFF# Netscape HTTP Cookie File\r\n" +
            "# This file was generated by an extension\r\n" +
            ".google.com\tTRUE\t/\tTRUE\t1999999999\tSID\tgoogle-secret\r\n" +
            ".youtube.com\tTRUE\t/\tTRUE\t1999999999\tSAPISID\tyt\r\n" +
            "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1999999999\tLOGIN_INFO\tlogin\r\n" +
            "music.youtube.com\tFALSE\t/\tTRUE\t1999999999\tPREF\tm\r\n" +
            ".notyoutube.com\tTRUE\t/\tTRUE\t1999999999\tSAPISID\tevil\r\n" +
            "broken line\r\n"
        val filtered = NetscapeCookies.youtubeOnly(export)
        assertEquals(
            listOf(
                "# Netscape HTTP Cookie File",
                "",
                ".youtube.com\tTRUE\t/\tTRUE\t1999999999\tSAPISID\tyt",
                "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1999999999\tLOGIN_INFO\tlogin",
                "music.youtube.com\tFALSE\t/\tTRUE\t1999999999\tPREF\tm",
                "",
            ),
            filtered.split("\n"),
        )
        assertTrue(NetscapeCookies.hasYouTubeSession(filtered))
        assertFalse(NetscapeCookies.hasYouTubeSession(NetscapeCookies.youtubeOnly(".google.com\tTRUE\t/\tTRUE\t1\tSAPISID\tx")))
    }
}
